name: Publish Widgets

on:
  push:
    branches: test-publish

jobs:
  list-widgets:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/widgets/${{ matrix.widget }}
    steps:
      - name: List Widgets
        run: |
          echo "widgets=[$(find . -maxdepth 1 -type d | awk 'NR>1' | sed 's|./||' | sed '/^\s*$/d' | paste -sd, -)]" >> $GITHUB_OUTPUT
  
  publish-all:
    needs: list-widgets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        widget: ${{ needs.list-widgets.outputs.widgets }}
    defaults:
      run:
        working-directory: src/widgets/${{ matrix.widget }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
